logging:
  level:
    org.springframework.security: INFO
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
spring:
  main:
    banner-mode: "off"
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
eureka:
  instance:
    preferIpAddress: false
  client:
    # Server doesnot required to register it self hence set to false
    registerWithEureka: false
    # Server Does not required to fetch the registry it self
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://na-registry:8761/eureka/
      